language: bash
before_install:
- sudo apt-get install texlive texlive-xetex texlive-math-extra texlive-latex-recommended
  texlive-latex-extra
- wget https://github.com/jgm/pandoc/releases/download/2.6/pandoc-2.6-linux.tar.gz
- tar xvfz pandoc-2.6-linux.tar.gz
script:
- bash deploy.sh
after_success:
- bash push.sh

# Build all branches, *including* gh-pages:
branches:
  only:
  - gh-pages
  - /.*/
